name: checks
on:
  pull_request:
  push:
  schedule:
    - cron: '18 18 * * *'
  workflow_dispatch:
jobs:
  checks:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4']
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php}}
          ini-values: short_open_tag=1
          tools: composer,phive
      - name: Checkout CMSimple_XH
        uses: actions/checkout@v4
        with:
          repository: cmsimple-xh/cmsimple-xh
          ref: '1.8.0'
          path: cmsimplexh
      - name: Checkout Plib_XH
        uses: actions/checkout@v4
        with:
          repository: cmb69/plib_xh
          path: cmsimplexh/plugins/plib
      - name: Checkout Ocal_XH
        uses: actions/checkout@v3
        with:
          path: 'cmsimplexh/plugins/ocal'
      - name: Cache Phive tools
        id: cache-tools
        uses: actions/cache@v4
        with:
          path: cmsimplexh/plugins/ocal/tools
          key: tools-${{hashFiles('cmsimplexh/plugins/ocal/.phive')}}
      - if: ${{steps.cache-tools.outputs.cache-hit != 'true'}}
        name: phive install
        run: cd cmsimplexh/plugins/ocal && phive --no-progress install --copy --force-accept-unsigned --trust-gpg-keys 51C67305FFC2E5C0,9093F8B32E4815AA,A978220305CD5C32,D5F0CB76E2DD74F8
      - name: composer install
        run: cd cmsimplexh/plugins/ocal && composer install
      - name: phing sniff
        run: cd cmsimplexh/plugins/ocal && PATH=tools:vendor/bin:$PATH phing sniff
      - name: phing stan
        run: cd cmsimplexh/plugins/ocal && PATH=tools:vendor/bin:$PATH phing stan
      - name: phing unit-tests
        run: cd cmsimplexh/plugins/ocal && PATH=tools:vendor/bin:$PATH phing test
